/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.cuni.mff.kovacspe.rbahodnotiacisoftver;

import java.io.FileInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.util.List;
import javax.swing.JOptionPane;

/**
 * Uvodny Form, ktory sluzi na administraciu sutaze
 *
 * @author Peter
 */
public class RBAForm extends javax.swing.JFrame {

    public void WriteTeams(List<Team> AllTeams) {
        //jTextArea1.setText(null);
        for (Team t : AllTeams) {

            jTextArea1.append(t.toString() + "\n");
        }
    }

    public void out(String s) {
        jTextArea1.append(s + "\n");
    }

    /**
     * Creates new form RBAForm
     */
    public RBAForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RBA administrácia");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("Vytvor prázdne výsledky");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Nacitaj timy");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Nacitaj timy z registracie");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Skonvertuj výsledky do .tex");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 405, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleDescription("RBA administrácia");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        RBAHodnotiaciSoftver.MakeEmptyResultFiles();
        out("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        RBAHodnotiaciSoftver.LoadTeams();
        out("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        RBAHodnotiaciSoftver.LoadAndCreateTeams();
        out("");
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * Skusi previest vsetky vysledky do TeX formatu
     *
     * @param evt
     */
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try (ObjectInputStream in = new ObjectInputStream(new FileInputStream("VMFINALRESULTS.res"))) {
            List<TeamVM> teams = (List<TeamVM>) in.readObject();
            TeXConvertor.ConvertVMResultsToTeX(teams);
            out("Výsledková listina kategórie Vlastný model bola vytvorená");
        } catch (IOException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Nepodarilo sa načítať výsledky Vlastného modelu. Súbor \"VMFINALRESULTS.res\" nebol nebol nájdený alebo je poškodený.", "RBA", JOptionPane.WARNING_MESSAGE);
        }
        try (ObjectInputStream in = new ObjectInputStream(new FileInputStream("RCQualifFINALRESULTS.res"))) {
            List<TeamRC> teams = (List<TeamRC>) in.readObject();
            TeXConvertor.ConvertRCQualifiactionResultsToTeX(teams);
            out("Výsledková listina kategórie Racing - kvalifikácia bola vytvorená");
        } catch (IOException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Nepodarilo sa načítať výsledky Racing - kvalifikácia. Súbor \"RCQualifFINALRESULTS.res\" nebol nebol nájdený alebo je poškodený.", "RBA", JOptionPane.WARNING_MESSAGE);
        }
        try (ObjectInputStream in = new ObjectInputStream(new FileInputStream("RCFINALRESULTS.res"))) {
            List<RacingGroup> teams = (List<RacingGroup>) in.readObject();
            TeXConvertor.ConvertRCResultsToTeX(teams);
            out("Výsledková listina kategórie Racing - preteky bola vytvorená");
        } catch (IOException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Nepodarilo sa načítať výsledky Racing - kvalifikácia. Súbor \"RCFINALRESULTS.res\" nebol nebol nájdený alebo je poškodený.", "RBA", JOptionPane.WARNING_MESSAGE);
        }

        try (ObjectInputStream in = new ObjectInputStream(new FileInputStream("RVQualifFINALRESULTS.res"))) {
            List<TeamRV> teams = (List<TeamRV>) in.readObject();
            TeXConvertor.ConvertRVQualifResultsToTeX(teams);
            out("Výsledková listina kategórie Robotická výzva - kvalifikácia bola vytvorená");
        } catch (IOException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Nepodarilo sa načítať výsledky Roboticka vyzva - kvalifikácia. Súbor \"RVQualifFINALRESULTS.res\" nebol nebol nájdený alebo je poškodený.", "RBA", JOptionPane.WARNING_MESSAGE);
        }

        try (ObjectInputStream in = new ObjectInputStream(new FileInputStream("RVFINALRESULTS.res"))) {
            List<TeamRV> teams = (List<TeamRV>) in.readObject();
            TeXConvertor.ConvertRVResultsToTeX(teams);
            out("Výsledková listina kategórie Robotická výzva - turnaj bola vytvorená");
        } catch (IOException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Nepodarilo sa načítať výsledky Roboticka vyzva - finale. Súbor \"RVFINALRESULTS.res.res\" nebol nebol nájdený alebo je poškodený.", "RBA", JOptionPane.WARNING_MESSAGE);
        }
        out("");
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
